title: GPIO music box
hero_image: images/banner.png
description: Make a device that plays music when you push its buttons.
original_url: https://www.raspberrypi.org/learning/gpio-music-box/
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-1, manufacture-0, community-0
interests: music
technologies: python, electronic-components
hardware: electronic-components
software: python
site_areas: projects
version: 4
last_tested: 2019-08-12
steps: 
- title: Introduction
- title: Setting up your project
- title: Converting your files
- title: Playing sounds
- title: Wiring buttons
- title: Playing sounds with buttons
- title: Improving the script
- title: "Challenge: a mobile disco"